### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by ebergam** [RicostruzioneTrasparente/albopop-json-converter#1]
@jenkin, guarda gli import qui: https://github.com/RicostruzioneTrasparente/albopop-json-converter/blob/develop/AlbopopJsonConverter.py

`from .AlbopopJsonValidator import AlbopopJsonValidator`
Ci deve essere quel punto?

**Comment by jenkin** [comment]
Quel punto è frutto di numerose imprecazioni contro il meraviglioso mondo dei moduli in python, quindi sì, in teoria è corretto... cosa non ti torna?

**Comment by jenkin** [comment]
Ah, vero, non va... ma forse ho capito perché...

**Comment by ebergam** [comment]
@jenkin :)
